# Allow connections from Docker network
service imap-login {
  inet_listener imap {
    port = 143
    address = *
  }
  inet_listener imaps {
    port = 993
    ssl = yes
    address = *
  }
}

service lmtp {
  inet_listener lmtp {
    address = *
    port = 24
  }
}

# Trust the Docker networks
login_trusted_networks = 172.16.0.0/12 10.0.0.0/8 192.168.0.0/16
